linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/andinger/tally-form-cli

issues:
  exclude-use-default: false
